export const styles = {
    container: {
      maxWidth: '1200px',
      margin: '0 auto',
      padding: '40px 20px',
      fontFamily: 'Arial, sans-serif',
      position: 'relative',
      zIndex: 1,
    },
    backgroundAnimation: {
      position: 'fixed',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      background: `
        radial-gradient(circle at 0% 0%, rgba(147, 51, 234, 0.1) 0%, transparent 50%),
        radial-gradient(circle at 100% 0%, rgba(59, 130, 246, 0.1) 0%, transparent 50%),
        radial-gradient(circle at 50% 100%, rgba(99, 102, 241, 0.1) 0%, transparent 50%)
      `,
      animation: 'gradientShift 15s ease infinite',
      zIndex: 0,
    },
    header: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      marginBottom: '40px',
      position: 'relative',
    },
    titleContainer: {
      position: 'relative',
      padding: '20px 0',
    },
    title: {
      fontSize: '4.5rem',
      fontWeight: '900',
      textAlign: 'center',
      background: 'linear-gradient(45deg, #9333ea 0%, #3b82f6 50%, #6366f1 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      marginTop: '20px',
      textShadow: '0 0 30px rgba(147, 51, 234, 0.3)',
      letterSpacing: '-2px',
      position: 'relative',
      animation: 'titleFloat 6s ease-in-out infinite',
    },
    subtitle: {
      fontSize: '1.2rem',
      color: '#6b7280',
      textAlign: 'center',
      marginTop: '10px',
      fontWeight: '500',
      letterSpacing: '1px',
    },
    nav: {
      display: 'flex',
      justifyContent: 'center',
      marginBottom: '32px',
      gap: '20px',
    },
    navButton: {
      padding: '14px 28px',
      fontSize: '1rem',
      fontWeight: 'bold',
      color: 'white',
      backgroundColor: '#6366f1',
      border: 'none',
      borderRadius: '12px',
      cursor: 'pointer',
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      textDecoration: 'none',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      boxShadow: '0 4px 6px rgba(99, 102, 241, 0.2)',
    },
    navButtonHover: {
      backgroundColor: '#4f46e5',
      transform: 'translateY(-2px)',
      boxShadow: '0 8px 12px rgba(99, 102, 241, 0.3)',
    },
  };