export const styles = {
    container: {
      minHeight: '100vh',
      position: 'relative',
      overflow: 'hidden',
      padding: '20px',
    },
    backgroundAnimation: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'linear-gradient(45deg, #f3f4f6 0%, #ffffff 100%)',
      zIndex: -1,
    },
    header: {
      marginBottom: '40px',
      padding: '20px',
      borderRadius: '12px',
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    },
    titleContainer: {
      textAlign: 'center',
      marginBottom: '24px',
    },
    title: {
      fontSize: '2.5rem',
      fontWeight: 'bold',
      color: '#1a1a1a',
      margin: '0',
      marginBottom: '8px',
    },
    subtitle: {
      fontSize: '1.1rem',
      color: '#666',
      margin: '0',
    },
    nav: {
      display: 'flex',
      justifyContent: 'center',
      gap: '20px',
    },
    navButton: {
      display: 'flex',
      alignItems: 'center',
      padding: '12px 24px',
      backgroundColor: '#6366f1',
      color: 'white',
      textDecoration: 'none',
      borderRadius: '8px',
      transition: 'all 0.3s ease',
      fontWeight: '500',
      '&:hover': {
        backgroundColor: '#4f46e5',
        transform: 'translateY(-2px)',
      },
    },
  };